version: '3.8'

services:
  service1:
    build:
      context: ./service1
    ports:
      - "3001:3000"
    environment:
      - MONGO_URI=mongodb://mongo:27017/service1
    depends_on:
      - mongo

  service2:
    build:
      context: ./service2
    ports:
      - "3002:3000"
    environment:
      - MONGO_URI=mongodb://mongo:27017/service2
    depends_on:
      - mongo

  service3:
    build:
      context: ./service3
    ports:
      - "3003:3000"
    environment:
      - MONGO_URI=mongodb://mongo:27017/service3
    depends_on:
      - mongo

  mongo:
    image: mongo:latest
    volumes:
      - mongo-data:/data/db
    ports:
      - "27017:27017"

volumes:
  mongo-data:
